AvoidOutlineForSingleExample:
    Enabled: true
AvoidFullStop:
    Enabled: true
AvoidScripting:
    Enabled: true
BackgroundDoesMoreThanSetup:
    Enabled: true
BackgroundRequiresMultipleScenarios:
    Enabled: true
BadScenarioName:
    Enabled: true
FileNameDiffersFeatureName:
    Enabled: true
GivensAfterBackground:
    Enabled: true
MissingExampleName:
    Enabled: true
MissingFeatureDescription:
    Enabled: true
MissingFeatureName:
    Enabled: true
MissingScenarioName:
    Enabled: true
MissingTestAction:
    Enabled: true
MissingVerification:
    Enabled: true
InvalidFileName:
    Enabled: true
InvalidStepFlow:
    Enabled: true
RequiredTagsStartsWith:
    Enabled: false
SameTagForAllScenarios:
    Enabled: true
ScenarioNamesMatch:
    Enabled: false
TagUsedMultipleTimes:
    Enabled: true
TooClumsy:
    Enabled: true
TooManyDifferentTags:
    Enabled: true
    MaxCount: 3
TooManySteps:
    Enabled: true
    MaxCount: 10
TooManyTags:
    Enabled: true
    MaxCount: 3
TooLongStep:
    Enabled: true
    MaxLength: 80
UniqueScenarioNames:
    Enabled: true
UnknownVariable:
    Enabled: true
UnusedVariable:
    Enabled: true
UseBackground:
    Enabled: true
UseOutline:
    Enabled: true
