#!/usr/bin/env ruby
# frozen_string_literal: true

require 'language_server-protocol'
require 'logger'
require 'optparse'
require 'uri'

require 'chutney'
require 'chutney/lsp'
require 'chutney/lsp/result'
require 'chutney/lsp/server'

OptionParser.new do |opts|
  opts.banner = 'Usage: chutney-lsp'

  opts.on('-v', '--version', 'Display the version.') do
    puts Chutney::VERSION
    exit
  end
end.parse!

Chutney::LSP::Server.new.start
