remote_theme: pmarsceill/just-the-docs
logo: "https://raw.githubusercontent.com/BillyRuffian/chutney/master/docs/logo.png"
title: Chutney
description: A linter for Gherkin
aux_links:
  "Chutney on GitHub":
    - "https://github.com/BillyRuffian/chutney"
footer_content: "Copyright &copy; 2019-2020 Nigel Brookes-Thomas. Distributed by an <a href=\"https://github.com/BillyRuffian/chutney/blob/master/LICENSE.txt\">MIT license.</a>"
